### ISSUE TITLE
Clicking `clear` button in Locale selection field causes server-side exception

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/vaadin-time-picker-flow#25] opened 2019-03-06 15:16 UTC
Steps to reproduce:
1. Go to https://vaadin.com/components/vaadin-time-picker/java-examples
2. Click `X` in the locale selection field

Outcome:

Unhandled *NullPointerException* on page https://vaadin.com/components/vaadin-time-picker/java-examples
```Locale must not be null.```
> ...
> com.vaadin.flow.component.timepicker.demo.TimePickerView.lambda$createLocalizedTimePicker$ea26d33e$1(TimePickerView.java:69)
> ...

**Comment by denis-anisimov** [comment] 2019-03-07 06:26
Duplicate of #17 17

**Closed as completed by denis-anisimov** 2019-03-07 06:26 UTC
