### ISSUE TITLE
Component demo "Time Picker With Step Setting" throws NPE when clearing time value field

### ISSUE THREAD

**Issue by paulroemer** [vaadin/vaadin-time-picker-flow#94] opened 2020-05-11 05:22 UTC
Where: 
- https://preview.vaadin.com/components/vaadin-time-picker/java-examples  (14.1.27)
- https://vaadin.com/components/vaadin-time-picker/java-examples (14.1.18)

What:
Select a time, delete it again and press enter.

```
vaadin.com(opens in new tab)APP Unhandled NullPointerException on page https://vaadin.com/components/vaadin-time-picker/java-examples

com.vaadin.flow.component.timepicker.demo.TimePickerView.lambda$createTimePickerWithStepSetting$1da64346$1(TimePickerView.java:150)
```

**Comment by Haprog** [comment] 2020-05-11 06:40
The problem is this event listener that doesn't have a null check for the value: https://github.com/vaadin/vaadin-time-picker-flow/blob/2.0.6/vaadin-time-picker-flow-demo/src/main/java/com/vaadin/flow/component/timepicker/demo/TimePickerView.java#L150

```java
        timePicker.addValueChangeListener(event -> {
            LocalTime value = event.getValue();
            localTimeValue.setText(String.format(localTimeValueFormat,
                    value.getHour(), value.getMinute(), value.getSecond(), // <- value is null when set to empty on client
                    value.get(ChronoField.MILLI_OF_SECOND)));
        });
```

Very easy to fix.

**Comment by web-padawan** [comment] 2020-07-23 12:05
Fixed by #102

**Closed as completed by web-padawan** 2020-07-23 12:05 UTC
Labels: bug, good first issue, documentation
